sudo: required
services:
   - docker
before_install:
   - docker build -t abdullahab4/docker-react -f dockerfile.dev .
script:
   - docker run -e CI=true abdullahab4/docker-react npm run test -- --coverage

